services:
  mongo:
    image: mongo:7.0.9
    container_name: mongo
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=
    #   - MONGO_INITDB_ROOT_PASSWORD=
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-18-alpine3.19
    container_name: mongo-express
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=johe
      - ME_CONFIG_BASICAUTH_PASSWORD=wazza
    ports:
      - "8081:8081"

volumes:
  mongo-data:
